22 = "Whisper"
50 = "Whisper"
86 = "Whisper"
19 = "Whisper"
36 = "Whisper"

[5]
Normal = [5.507433, 6.208682]

[44]
Normal = [5.086358, 5.4074745]

[105]
Normal = [5.4657664, 6.0313325]

[10]
Normal = [5.6480374, 6.13957]

[24]
Normal = [5.3596554, 6.040487]

[102]
Normal = [5.4221168, 6.12452]

[73]
Normal = [5.1203723, 5.557046]

[59]
Normal = [5.53268, 5.9698334]

[41]
Normal = [4.586253, 5.125668]

[96]
Normal = [4.815563, 5.4092994]

[52]
Normal = [4.3069367, 5.09945]

[51]
Normal = [4.556119, 5.443242]

[101]
Normal = [4.3452787, 4.6932783]

[48]
Normal = [5.4161296, 5.9573627]

[46]
Normal = [5.419875, 5.903794]

[37]
Normal = [5.1631374, 5.6713533]

[43]
Normal = [5.320423, 5.877638]

[70]
Normal = [5.6756916, 6.2963805]

[94]
Normal = [4.9252377, 5.598667]

[49]
Normal = [5.477053, 5.8314834]

[71]
Normal = [2.312346, 4.6686883]

[82]
Normal = [4.2943354, 4.8610106]

[88]
Normal = [5.0121155, 5.5460863]

[90]
Normal = [5.2476273, 5.9458547]

[33]
Normal = [5.1881037, 5.7690744]

[13]
Normal = [4.3045096, 5.100669]

[84]
Normal = [3.8549597, 4.817555]

[103]
Normal = [5.582282, 6.177609]

[30]
Normal = [4.9595428, 5.6706595]

[27]
Normal = [5.2081237, 5.845956]

[2]
Normal = [5.321701, 6.0094457]

[14]
Normal = [5.2232823, 5.7196727]

[34]
Normal = [4.9232054, 5.6543317]

[56]
Normal = [5.034725, 5.7351694]

[0]
Normal = [5.365475, 5.9520664]

[79]
Normal = [5.5661035, 6.0209937]

[6]
Normal = [5.2837415, 5.889922]

[55]
Normal = [5.0540457, 5.776067]

[93]
Normal = [5.4734745, 6.172895]

[38]
Normal = [5.353126, 5.6656914]

[62]
Normal = [5.457497, 5.8348846]

[67]
Normal = [4.7192945, 5.387093]

[21]
Normal = [4.496267, 5.294566]

[75]
Normal = [5.451346, 6.056415]

[85]
Normal = [4.3543677, 4.889055]

[45]
Normal = [5.252045, 5.704029]

[42]
Normal = [4.3665743, 5.8421745]

[20]
Normal = [5.3825555, 5.9076643]

[11]
Normal = [4.5815606, 5.294161]

[100]
Normal = [4.482997, 5.3204575]

[107]
Normal = [5.4194274, 6.0882206]

[109]
Normal = [5.09904, 5.7690206]

[23]
Normal = [5.261228, 5.877413]

[112]
Normal = [5.6477213, 6.4069843]

[89]
Normal = [5.5242343, 5.876825]

[7]
Normal = [5.421184, 6.037995]

[104]
Normal = [5.5913496, 6.00419]

[58]
Normal = [5.52928, 6.1800103]

[57]
Normal = [5.103133, 5.854031]

[66]
Normal = [5.2473764, 5.7771845]

[25]
Normal = [5.329394, 5.6944175]

[63]
Normal = [5.53062, 6.00777]

[99]
Normal = [4.446147, 4.9093437]

[3]
Normal = [5.412321, 6.1838365]

[15]
Normal = [5.4909625, 6.0933747]

[97]
Normal = [5.364362, 6.0074315]

[32]
Normal = [5.127786, 5.6639404]

[29]
Normal = [5.1334014, 5.767421]

[80]
Normal = [5.3359504, 5.8515606]

[9]
Normal = [5.102991, 5.8592463]

[91]
Normal = [5.285026, 5.786753]

[98]
Normal = [5.2253304, 5.783393]

[1]
Normal = [5.530851, 6.215691]

[106]
Normal = [5.271167, 5.84379]

[40]
Normal = [4.686222, 5.4378166]

[108]
Normal = [5.1093016, 5.7487054]

[64]
Normal = [5.3993483, 5.888894]

[92]
Normal = [5.3148956, 6.030013]

[60]
Normal = [5.6137333, 6.098184]

[76]
Normal = [5.97988, 6.470624]

[4]
Normal = [5.369445, 5.9466]

[35]
Normal = [5.4552226, 6.16435]

[8]
Normal = [5.4568987, 6.127592]

[81]
Normal = [4.3578157, 5.3278575]

[111]
Normal = [5.303159, 5.7755494]

[68]
Normal = [5.3954687, 6.206823]

[31]
Normal = [5.067166, 5.649382]

[28]
Normal = [5.2900367, 6.180675]

[12]
Normal = [4.703694, 5.401971]

[47]
Normal = [5.32138, 5.7864294]

[39]
Normal = [5.0441093, 5.6584454]

[87]
Normal = [5.303389, 6.18434]

[16]
Normal = [5.205302, 5.8448124]

[26]
Normal = [5.6050296, 6.214481]

[54]
Normal = [5.3959274, 6.101776]

[65]
Normal = [5.14099, 6.0748434]

[110]
Normal = [5.300578, 6.2361264]

[17]
Normal = [5.3311977, 6.002695]

[74]
Normal = [5.312985, 5.9982495]

[72]
Normal = [5.5151415, 6.2160993]

[77]
Normal = [5.6029625, 5.9802237]

[53]
Normal = [4.436597, 5.405046]

[61]
Normal = [5.1966276, 5.6386404]

[18]
Normal = [5.2972255, 5.889795]

[78]
Normal = [5.462966, 6.0364647]

[83]
Normal = [4.312664, 5.103295]

[95]
Normal = [5.068045, 5.7665787]

[69]
Normal = [5.3107505, 6.017738]
